// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsxVq02BDxk4WFH6LZ4KjjbCFO5fjohaY',
    appId: '1:399247480428:web:5a5adca4c413a3f2312a49',
    messagingSenderId: '399247480428',
    projectId: 'flutter-firebase-d99d4',
    authDomain: 'flutter-firebase-d99d4.firebaseapp.com',
    storageBucket: 'flutter-firebase-d99d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXne9WOdVIoVKiXoohjAcmHoyptqLhSAM',
    appId: '1:399247480428:android:696681a7f4c5d5f4312a49',
    messagingSenderId: '399247480428',
    projectId: 'flutter-firebase-d99d4',
    storageBucket: 'flutter-firebase-d99d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZIdcUvEVT5rJrZEPjNcX_YiBfL3SOHOE',
    appId: '1:399247480428:ios:d22c2f2ab721d143312a49',
    messagingSenderId: '399247480428',
    projectId: 'flutter-firebase-d99d4',
    storageBucket: 'flutter-firebase-d99d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZIdcUvEVT5rJrZEPjNcX_YiBfL3SOHOE',
    appId: '1:399247480428:ios:d22c2f2ab721d143312a49',
    messagingSenderId: '399247480428',
    projectId: 'flutter-firebase-d99d4',
    storageBucket: 'flutter-firebase-d99d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsxVq02BDxk4WFH6LZ4KjjbCFO5fjohaY',
    appId: '1:399247480428:web:620713b8a00ac990312a49',
    messagingSenderId: '399247480428',
    projectId: 'flutter-firebase-d99d4',
    authDomain: 'flutter-firebase-d99d4.firebaseapp.com',
    storageBucket: 'flutter-firebase-d99d4.firebasestorage.app',
  );
}
